### ISSUE TITLE
Feature request: asynchronous mapping

### ISSUE THREAD

**Issue by taeke** [ArcadyIT/AutoMapper#3]
As discussed yesterday: It would be great to have an extra mapping function which does not return the result but accepts a callback. It would make it possible, for example when you're working in an angular environment which has promisses, to do something (in pseudo code) like this:

automapper
    .createMap(fromKey, toKey)
    .convertUsing(function (resolutionContext : AutoMapperJs.IResolutionContext) {
        someApiCallBaseOnOrignalObject().then(function (result) 
          resolutionContext.callBack({ propA: resolutionContext.sourceValue.propA, propB: result}) }
        );
    });

automapper.mapAsync(fromKey, toKey, originalObject, function(result) { console.log(result) });

**Comment by loedeman** [comment]
Hi Taeke,

Thanks for suggesting. I will look into technical feasibility for this feature request in the nearby future. This feature will probably not be used very often (although there certainly is a use case for it, in particular where custom type converters are used), therefore it should not slow down 'normal' automapper execution.

I will keep you posted!

Cheers, Bert

**Comment by taeke** [comment]
5:35 AM :) 
autmapper.map('ISource', 'ng.IPromise<IDestination>').then

**Comment by taeke** [comment]
https://github.com/taeke/AsyncAutomapper

**Comment by loedeman** [comment]
Thanks Taeke! I am currently implementing full asynchronous mapping support in AutoMapper. Just wait a couple of days for me to remove some sharp edges before giving it a try ;) ... Of course, you can already have a look at the source code ;) ...

**Comment by loedeman** [comment]
Asynchronous mapping is now fully supported in AutoMapper on createMap.forMember, createMap.forSourceMember and createMap.convertUsing functions. When using asynchronous mapping, it is not possible to use the synchronous map function, use mapAsync instead.
